### ISSUE TITLE
update doc

### ISSUE THREAD

**Issue by killerwolf** [kronostechnologies/kronos-log#6]
i have the folowwing error trying the first example

`Argument 2 passed to Kronos\Log\Writer\File::__construct() must be an instance of Kronos\Log\Adaptor\FileFactory, none given`

Replacing this line:
`$debug = new Kronos\Log\Writer\File('../var/log/api.log', (new Kronos\Log\Adaptor\FileFactory()));`
with this
`$debug = new Kronos\Log\Writer\File('../var/log/api.log');`
fixed it

**Comment by jbreton** [comment]
Thanks for the heads-up.

I fixed the exemple.
